# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "528b4c2ec9b3ebdfc8cb6fce7d36ca67"
name = "GMPauto"
application_url = "https://samplemakeer.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_inventory,write_discounts"

[app_proxy]
url = "https://samplemakeer.onrender.com/proxy"
prefix = "apps"
subpath = "gwp"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  # Mandatory GDPR/CCPA compliance topics. Handled by:
  # /app/routes/webhooks.customers.data_request.tsx
  # /app/routes/webhooks.customers.redact.tsx
  # /app/routes/webhooks.shop.redact.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://samplemakeer.onrender.com/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
