api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "gwp-free-gift-discount"
uid = "f57057de-2aee-c718-96e7-99d806b8b365f34b142d"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
  watch = ["src/**/*.js"]
